name: Auto Deploy on Push

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan remote-server >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no x@146.190.199.222 "cd ~/SimulshiftGo && git pull"
