name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.5
        with:
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/simulshiftgo"
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/simulshiftgo
            docker build -t simulshiftgo:${{ github.sha }} .
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 9001:9001 simulshiftgo:${{ github.sha }}
